name: librsync
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  cryptography: ^2.5.0
  pointycastle: ^3.7.3
  async: ^2.11.0
  tuple: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  benchmark_harness: ^2.2.2
